name: "🚀 Déploiement"

on:
  push:
    branches: [master]
    paths:
      - ".github/workflows/deploy.yml"
      - "content/**"
      - "mkdocs.yml"
      - "requirements*.txt"

jobs:
  deploy:
    name: "📤 GitHub Pages"

    runs-on: ubuntu-latest

    if: ${{ github.repository_owner == 'geotribu' }}

    steps:
      - name: Get source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: "pip"

      - name: Install dependencies
        env:
          GH_TOKEN_MATERIAL_INSIDERS: ${{ secrets.GH_TOKEN_MATERIAL_INSIDERS }}
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade -r requirements-insiders.txt
          python -m pip install --upgrade ghp-import

      - name: Cache build dependencies (external assets downloaded)
        uses: actions/cache@v3
        with:
          key: ${{ github.ref }}
          path: .cache

      - name: Build static website
        run: |
          python scripts/mkdocs_config_merger.py -c mkdocs.yml
          mkdocs build --clean --config-file mkdocs.yml --verbose --strict
        env:
          MKDOCS_ENABLE_PLUGIN_GIT_AUTHORS: true
          MKDOCS_ENABLE_PLUGIN_GIT_COMMITTERS: true
          MKDOCS_ENABLE_PLUGIN_GIT_DATES: true
          MKDOCS_ENABLE_PLUGIN_PRIVACY: true
          MKDOCS_ENABLE_PLUGIN_RSS: true
          MKDOCS_GOOGLE_ANALYTICS_KEY: ${{ secrets.GOOGLE_ANALYTICS_KEY }}

      - name: Deploy to Github Pages
        run: |
          git config --global user.name "Geotribu (Github Action)"
          git config --global user.email "geotribu@gmail.com"
          ghp-import --force --message="Site Geotribu déployé" --no-jekyll --no-history --push build/mkdocs/site
